services:
  - type: web
    name: computer-lab-inventory-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/angular-signup-verification-boilerplate
    envVars:
      - key: API_URL
        value: https://computer-lab-inventory-backend.onrender.com
